# Generated by Django 4.0.2 on 2022-02-24 17:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('buscas', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Configurações',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Dias_Salvos', models.IntegerField(max_length=2)),
            ],
        ),
        migrations.CreateModel(
            name='Paridades',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=6)),
            ],
        ),
    ]
