# Generated by Django 4.0.2 on 2022-02-27 18:32

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('buscas', '0003_configuraçõe_rename_paridades_paridade_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='configuraçõe',
            old_name='Dias_Salvos',
            new_name='dias_salvos',
        ),
        migrations.AlterField(
            model_name='paridade',
            name='name',
            field=models.CharField(max_length=6, validators=[django.core.validators.RegexValidator('^[A-Z_]*$', 'Apenas Letras maiúsculas permitidas')]),
        ),
    ]
