# Generated by Django 4.0.2 on 2022-02-27 18:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('buscas', '0004_rename_dias_salvos_configuraçõe_dias_salvos_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Post',
        ),
    ]
