# Generated by Django 4.0.2 on 2022-02-27 18:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('buscas', '0005_delete_post'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Configuraçõe',
        ),
    ]
