# Generated by Django 4.0.2 on 2022-02-27 18:40

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('buscas', '0006_delete_configuraçõe'),
    ]

    operations = [
        migrations.CreateModel(
            name='Configuraçõe',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('login', models.CharField(max_length=32)),
                ('senha', models.CharField(max_length=32)),
                ('dias_salvos', models.PositiveIntegerField(default=10, validators=[django.core.validators.MaxValueValidator(50), django.core.validators.MinValueValidator(1)])),
            ],
        ),
    ]
