# Generated by Django 4.0.2 on 2022-02-28 21:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('buscas', '0008_chance'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Chance',
        ),
    ]
