# Generated by Django 4.0.2 on 2022-03-01 12:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('buscas', '0010_chance'),
    ]

    operations = [
        migrations.AlterField(
            model_name='chance',
            name='direc',
            field=models.CharField(choices=[('CALL', 'COMPRA'), ('SELL', 'VENDA')], max_length=32),
        ),
        migrations.AlterField(
            model_name='chance',
            name='timeframe',
            field=models.PositiveSmallIntegerField(choices=[(1, '1'), (5, '5'), (15, '15')]),
        ),
    ]
