# Generated by Django 4.0.2 on 2022-03-03 19:52

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('buscas', '0011_alter_chance_direc_alter_chance_timeframe'),
    ]

    operations = [
        migrations.AlterField(
            model_name='chance',
            name='par',
            field=models.CharField(max_length=32, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='paridade',
            name='name',
            field=models.CharField(max_length=6, unique=True, validators=[django.core.validators.RegexValidator('^[A-Z_]*$', 'Apenas Letras maiúsculas permitidas')]),
        ),
        migrations.AlterUniqueTogether(
            name='chance',
            unique_together={('par', 'timeframe', 'hora', 'minuto')},
        ),
        migrations.RemoveField(
            model_name='chance',
            name='id',
        ),
    ]
