# Generated by Django 4.0.2 on 2022-03-03 19:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('buscas', '0012_alter_chance_par_alter_paridade_name_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Chance',
        ),
    ]
