# Generated by Django 4.0.2 on 2022-03-04 11:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('buscas', '0014_chance'),
    ]

    operations = [
        migrations.CreateModel(
            name='vela',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('par', models.CharField(max_length=32)),
                ('data', models.TimeField()),
                ('timeframe', models.PositiveSmallIntegerField(choices=[(1, '1'), (5, '5'), (15, '15')])),
                ('hora', models.PositiveSmallIntegerField()),
                ('minuto', models.PositiveSmallIntegerField()),
                ('direc', models.CharField(choices=[('CALL', 'COMPRA'), ('SELL', 'VENDA')], max_length=32)),
            ],
        ),
    ]
