# Generated by Django 4.0.2 on 2022-03-04 14:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('buscas', '0015_vela'),
    ]

    operations = [
        migrations.DeleteModel(
            name='vela',
        ),
    ]
