# Generated by Django 4.0.2 on 2022-03-07 13:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('buscas', '0017_vela'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Configuraçõe',
            new_name='Configuração',
        ),
        migrations.AlterModelOptions(
            name='configuração',
            options={'verbose_name_plural': 'configurações'},
        ),
    ]
